# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.timesfm_pb2 as timesfm__pb2


class PredictAgriStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict_metric = channel.stream_stream(
                '/PredictAgri/predict_metric',
                request_serializer=timesfm__pb2.prev_values.SerializeToString,
                response_deserializer=timesfm__pb2.future_values.FromString,
                )


class PredictAgriServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict_metric(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictAgriServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict_metric': grpc.stream_stream_rpc_method_handler(
                    servicer.predict_metric,
                    request_deserializer=timesfm__pb2.prev_values.FromString,
                    response_serializer=timesfm__pb2.future_values.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictAgri', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictAgri(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict_metric(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/PredictAgri/predict_metric',
            timesfm__pb2.prev_values.SerializeToString,
            timesfm__pb2.future_values.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
